use std::fmt::{Display, Formatter};

pub struct BasicInformation {
    pub x: u32,
    pub y: u32,
}

#[derive(Debug)]
pub struct CpuPlayerInformation {
    pub x: u32,
    pub y: u32,
    pub list_1: u32,
    pub list_2: u32,
    pub list_3: u32,
    pub list_4: u32,
    pub default_units: [u16; 3],
}

pub enum UnitKind {
    UnknownUnit(u8),
    TargetArea,
    CpuPlayerInformation,
    DetentionCenter,
    NewDetentionCenter,
    MapConfiguration,
    PatrolPoint,
    MatrixAnimation,
    ScrollStart,
    Reinforcements,
    EvolvedAltaroftheScourge,
    Hut,
    OilPatch,
    EvolvedWaspBomber,
    EvolvedPteradonFighter,
    EvolvedBatCarrier,
    EvolvedArmoury,
    EvolvedWarriorHall,
    EvolvedGasPen,
    EvolvedGasPlant,
    EvolvedDrillRig,
    EvolvedBeastEnclosure,
    EvolvedClanhall,
    EvolvedPowerStation,
    EvolvedHealingTent,
    EvolvedAlchemyHall,
    EvolvedDemon,
    EvolvedPyromaniac,
    EvolvedRioter,
    EvolvedBezerker,
    EvolvedMartyr,
    EvolvedBazookoid,
    EvolvedSpiritArcher,
    EvolvedMekanik,
    EvolvedKneecapper,
    EvolvedWormTower,
    EvolvedBallistaBattery,
    EvolvedTouchofDeath,
    EvolvedBombardierMegaBeetl,
    EvolvedMissileCrab,
    EvolvedCrinoid,
    EvolvedDeathHippo,
    EvolvedDireWolf,
    EvolvedWarMastodon,
    EvolvedMobileDerrick,
    EvolvedMobileClanHall,
    EvolvedPitScorpion,
    EvolvedBullAntTanker,
    EvolvedSkeletalWall,
    EvolvedSpiritWall,
    Series9CropDuster,
    Series9AgResponsebot,
    Series9TransportDome,
    Series9WeaponControl,
    Series9MicrounitFactory,
    Series9Windmill,
    Series9WindTurbine,
    Series9DrillRig,
    Series9MacrounitFactory,
    Series9Barn,
    Series9PowerStation,
    Series9MaintenanceDepot,
    Series9Technostudy,
    Series9WeedKiller,
    Series9PodLauncher,
    Series9Seeder,
    Series9Michaelangelo,
    Series9Pollinator,
    Series9Deseeder,
    Series9Systech,
    Series9DistanceSeeder,
    Series9PodCannon,
    Series9SolarIntensifier,
    Series9BugZapper,
    Series9Cauteriser,
    Series9DoomDome,
    Series9GrimReaper,
    Series9MobileOilbot,
    Series9MobileBarn,
    Series9Patrolbot,
    Series9Radiator,
    Series9Responsebot,
    Series9Tankbot,
    Series9OilTankerbot,
    Series9PowerHedge,
    Series9LaserWall,
    SurvivorWilburBomber,
    SurvivorOrvilleFighter,
    SurvivorTransportChopper,
    SurvivorArmoury,
    SurvivorBarracks,
    SurvivorSolarCollector,
    SurvivorSolarConvertor,
    SurvivorDrillRig,
    SurvivorMachineShop,
    SurvivorOutpost,
    SurvivorPowerStation,
    SurvivorRepairBay,
    SurvivorResearchLaboratory,
    SurvivorCaptive,
    SurvivorFlamer,
    SurvivorGrenadier,
    SurvivorMachineGunner,
    SurvivorKamikaze,
    SurvivorGuidedRocketeer,
    SurvivorLaserRifleman,
    SurvivorTechnician,
    SurvivorLightDefenseTower,
    SurvivorCannonTower,
    SurvivorAaTower,
    SurvivorLaserDestroyer,
    SurvivorAtv,
    SurvivorAnacondaTank,
    SurvivorAutocannonTank,
    SurvivorBarrageCraft,
    SurvivorDirtBike,
    SurvivorHoverBuggy,
    SurvivorJuggernaut,
    SurvivorMobileDrillRig,
    SurvivorMobileOutpost,
    SurvivorOilTanker,
    SurvivorHydrorockWall,
    SurvivorSolarWall,
    Tech21stCenturyDropship,
    Tech21stCenturyGortRobot,
    Tech21stCenturyMechanoidWalker,
    Tech21stCenturyPlasmaTankMk2,
    Tech21stCenturySentinelDroid,
    Tech21stCenturyTechBunker,
    Tech21stCenturyUfo,
    Ripple,
}

impl Display for UnitKind {
    fn fmt(&self, f: &mut Formatter) -> core::fmt::Result {
        let value = match self {
            UnitKind::UnknownUnit(kind) => "Unknown Unit",
            UnitKind::TargetArea => "Target Area",
            UnitKind::CpuPlayerInformation => "CPU Player Information",
            UnitKind::DetentionCenter => "Detention Center",
            UnitKind::NewDetentionCenter => "New Detention Center",
            UnitKind::MapConfiguration => "Map Configuration",
            UnitKind::PatrolPoint => "Patrol Point",
            UnitKind::MatrixAnimation => "Matrix Animation",
            UnitKind::ScrollStart => "Scroll Start",
            UnitKind::Reinforcements => "Reinforcements",
            UnitKind::EvolvedAltaroftheScourge => "Evolved Altar of the Scourge",
            UnitKind::Hut => "Hut",
            UnitKind::OilPatch => "Oil Patch",
            UnitKind::EvolvedWaspBomber => "Evolved Wasp Bomber",
            UnitKind::EvolvedPteradonFighter => "Evolved Pteradon Fighter",
            UnitKind::EvolvedBatCarrier => "Evolved Bat Carrier",
            UnitKind::EvolvedArmoury => "Evolved Armoury",
            UnitKind::EvolvedWarriorHall => "Evolved Warrior Hall",
            UnitKind::EvolvedGasPen => "Evolved Gas Pen",
            UnitKind::EvolvedGasPlant => "Evolved Gas Plant",
            UnitKind::EvolvedDrillRig => "Evolved Drill Rig",
            UnitKind::EvolvedBeastEnclosure => "Evolved Beast Enclosure",
            UnitKind::EvolvedClanhall => "Evolved Clan hall",
            UnitKind::EvolvedPowerStation => "Evolved Power Station",
            UnitKind::EvolvedHealingTent => "Evolved Healing Tent",
            UnitKind::EvolvedAlchemyHall => "Evolved Alchemy Hall",
            UnitKind::EvolvedDemon => "Evolved Demon",
            UnitKind::EvolvedPyromaniac => "Evolved Pyromaniac",
            UnitKind::EvolvedRioter => "Evolved Rioter",
            UnitKind::EvolvedBezerker => "Evolved Bezerker",
            UnitKind::EvolvedMartyr => "Evolved Martyr",
            UnitKind::EvolvedBazookoid => "Evolved Bazookoid",
            UnitKind::EvolvedSpiritArcher => "Evolved Spirit Archer",
            UnitKind::EvolvedMekanik => "Evolved Mekanik",
            UnitKind::EvolvedKneecapper => "Evolved Kneecapper",
            UnitKind::EvolvedWormTower => "Evolved Worm Tower",
            UnitKind::EvolvedBallistaBattery => "Evolved Ballista Battery",
            UnitKind::EvolvedTouchofDeath => "Evolved Touch of Death",
            UnitKind::EvolvedBombardierMegaBeetl => "Evolved Bombardier Mega-Beetl",
            UnitKind::EvolvedMissileCrab => "Evolved Missile Crab",
            UnitKind::EvolvedCrinoid => "Evolved Crinoid",
            UnitKind::EvolvedDeathHippo => "Evolved Death Hippo",
            UnitKind::EvolvedDireWolf => "Evolved Dire Wolf",
            UnitKind::EvolvedWarMastodon => "Evolved War Mastodon",
            UnitKind::EvolvedMobileDerrick => "Evolved Mobile Derrick",
            UnitKind::EvolvedMobileClanHall => "Evolved Mobile Clan Hall",
            UnitKind::EvolvedPitScorpion => "Evolved Pit Scorpion",
            UnitKind::EvolvedBullAntTanker => "Evolved Bull-Ant Tanker",
            UnitKind::EvolvedSkeletalWall => "Evolved Skeletal Wall",
            UnitKind::EvolvedSpiritWall => "Evolved Spirit Wall",
            UnitKind::Series9CropDuster => "Series 9 Crop Duster",
            UnitKind::Series9AgResponsebot => "Series 9 AG-Responsebot",
            UnitKind::Series9TransportDome => "Series 9 Transport Dome",
            UnitKind::Series9WeaponControl => "Series 9 Weapon Control",
            UnitKind::Series9MicrounitFactory => "Series 9 Microunit Factory",
            UnitKind::Series9Windmill => "Series 9 Windmill",
            UnitKind::Series9WindTurbine => "Series 9 Wind Turbine",
            UnitKind::Series9DrillRig => "Series 9 Drill Rig",
            UnitKind::Series9MacrounitFactory => "Series 9 Macrounit Factory",
            UnitKind::Series9Barn => "Series 9 Barn",
            UnitKind::Series9PowerStation => "Series 9 Power Station",
            UnitKind::Series9MaintenanceDepot => "Series 9 Maintenance Depot",
            UnitKind::Series9Technostudy => "Series 9 Technostudy",
            UnitKind::Series9WeedKiller => "Series 9 Weed Killer",
            UnitKind::Series9PodLauncher => "Series 9 Pod Launcher",
            UnitKind::Series9Seeder => "Series 9 Seeder",
            UnitKind::Series9Michaelangelo => "Series 9 Michaelangelo",
            UnitKind::Series9Pollinator => "Series 9 Pollinator",
            UnitKind::Series9Deseeder => "Series 9 Deseeder",
            UnitKind::Series9Systech => "Series 9 Systech",
            UnitKind::Series9DistanceSeeder => "Series 9 Distance Seeder",
            UnitKind::Series9PodCannon => "Series 9 Pod Cannon",
            UnitKind::Series9SolarIntensifier => "Series 9 Solar Intensifier",
            UnitKind::Series9BugZapper => "Series 9 Bug Zapper",
            UnitKind::Series9Cauteriser => "Series 9 Cauteriser",
            UnitKind::Series9DoomDome => "Series 9 Doom Dome",
            UnitKind::Series9GrimReaper => "Series 9 Grim Reaper",
            UnitKind::Series9MobileOilbot => "Series 9 Mobile Oilbot",
            UnitKind::Series9MobileBarn => "Series 9 Mobile Barn",
            UnitKind::Series9Patrolbot => "Series 9 Patrolbot",
            UnitKind::Series9Radiator => "Series 9 Radiator",
            UnitKind::Series9Responsebot => "Series 9 Responsebot",
            UnitKind::Series9Tankbot => "Series 9 Tankbot",
            UnitKind::Series9OilTankerbot => "Series 9 Oil Tankerbot",
            UnitKind::Series9PowerHedge => "Series 9 Power Hedge",
            UnitKind::Series9LaserWall => "Series 9 Laser Wall",
            UnitKind::SurvivorWilburBomber => "Survivor `Wilbur' Bomber",
            UnitKind::SurvivorOrvilleFighter => "Survivor `Orville' Fighter",
            UnitKind::SurvivorTransportChopper => "Survivor Transport Chopper",
            UnitKind::SurvivorArmoury => "Survivor Armoury",
            UnitKind::SurvivorBarracks => "Survivor Barracks",
            UnitKind::SurvivorSolarCollector => "Survivor Solar Collector",
            UnitKind::SurvivorSolarConvertor => "Survivor Solar Convertor",
            UnitKind::SurvivorDrillRig => "Survivor Drill Rig",
            UnitKind::SurvivorMachineShop => "Survivor Machine Shop",
            UnitKind::SurvivorOutpost => "Survivor Outpost",
            UnitKind::SurvivorPowerStation => "Survivor Power Station",
            UnitKind::SurvivorRepairBay => "Survivor Repair Bay",
            UnitKind::SurvivorResearchLaboratory => "Survivor Research Laboratory",
            UnitKind::SurvivorCaptive => "Survivor Captive",
            UnitKind::SurvivorFlamer => "Survivor Flamer",
            UnitKind::SurvivorGrenadier => "Survivor Grenadier",
            UnitKind::SurvivorMachineGunner => "Survivor Machine Gunner",
            UnitKind::SurvivorKamikaze => "Survivor Kamikaze",
            UnitKind::SurvivorGuidedRocketeer => "Survivor Guided Rocketeer",
            UnitKind::SurvivorLaserRifleman => "Survivor Laser Rifleman",
            UnitKind::SurvivorTechnician => "Survivor Technician",
            UnitKind::SurvivorLightDefenseTower => "Survivor Light Defense Tower",
            UnitKind::SurvivorCannonTower => "Survivor Cannon Tower",
            UnitKind::SurvivorAaTower => "Survivor AA Tower",
            UnitKind::SurvivorLaserDestroyer => "Survivor Laser Destroyer",
            UnitKind::SurvivorAtv => "Survivor ATV",
            UnitKind::SurvivorAnacondaTank => "Survivor Anaconda Tank",
            UnitKind::SurvivorAutocannonTank => "Survivor Autocannon Tank",
            UnitKind::SurvivorBarrageCraft => "Survivor Barrage Craft",
            UnitKind::SurvivorDirtBike => "Survivor Dirt Bike",
            UnitKind::SurvivorHoverBuggy => "Survivor Hover Buggy",
            UnitKind::SurvivorJuggernaut => "Survivor Juggernaut",
            UnitKind::SurvivorMobileDrillRig => "Survivor Mobile Drill Rig",
            UnitKind::SurvivorMobileOutpost => "Survivor Mobile Outpost",
            UnitKind::SurvivorOilTanker => "Survivor Oil Tanker",
            UnitKind::SurvivorHydrorockWall => "Survivor Hydrorock Wall",
            UnitKind::SurvivorSolarWall => "Survivor Solar Wall",
            UnitKind::Tech21stCenturyDropship => "21st Century Dropship",
            UnitKind::Tech21stCenturyGortRobot => "21st Century Gort Robot",
            UnitKind::Tech21stCenturyMechanoidWalker => "21st Century Mechanoid Walker",
            UnitKind::Tech21stCenturyPlasmaTankMk2 => "21st Century Plasma Tank Mk 2",
            UnitKind::Tech21stCenturySentinelDroid => "21st Century Sentinel Droid",
            UnitKind::Tech21stCenturyTechBunker => "21st Century Tech Bunker",
            UnitKind::Tech21stCenturyUfo => "21st Century UFO",
            UnitKind::Ripple => "Ripple",
        };
        write!(f, "{}", value)
    }
}

impl UnitKind {
    pub fn from_number(number: u8) -> Option<UnitKind> {
        match number {
            0x00 => Some(UnitKind::TargetArea),
            0x01 => Some(UnitKind::CpuPlayerInformation),
            0x02 => Some(UnitKind::DetentionCenter),
            0x03 => Some(UnitKind::NewDetentionCenter),
            0x04 => Some(UnitKind::MapConfiguration),
            0x06 => Some(UnitKind::PatrolPoint),
            0x07 => Some(UnitKind::MatrixAnimation),
            0x09 => Some(UnitKind::ScrollStart),
            0x0a => Some(UnitKind::Reinforcements),
            0x0b => Some(UnitKind::EvolvedAltaroftheScourge),
            0x0f => Some(UnitKind::Hut),
            0x10 => Some(UnitKind::OilPatch),
            0x11 => Some(UnitKind::EvolvedWaspBomber),
            0x13 => Some(UnitKind::EvolvedPteradonFighter),
            0x14 => Some(UnitKind::EvolvedBatCarrier),
            0x15 => Some(UnitKind::EvolvedArmoury),
            0x16 => Some(UnitKind::EvolvedWarriorHall),
            0x17 => Some(UnitKind::EvolvedGasPen),
            0x18 => Some(UnitKind::EvolvedGasPlant),
            0x19 => Some(UnitKind::EvolvedDrillRig),
            0x1a => Some(UnitKind::EvolvedBeastEnclosure),
            0x1b => Some(UnitKind::EvolvedClanhall),
            0x1c => Some(UnitKind::EvolvedPowerStation),
            0x1d => Some(UnitKind::EvolvedHealingTent),
            0x1e => Some(UnitKind::EvolvedAlchemyHall),
            0x1f => Some(UnitKind::EvolvedDemon),
            0x22 => Some(UnitKind::EvolvedPyromaniac),
            0x23 => Some(UnitKind::EvolvedRioter),
            0x24 => Some(UnitKind::EvolvedBezerker),
            0x25 => Some(UnitKind::EvolvedMartyr),
            0x26 => Some(UnitKind::EvolvedBazookoid),
            0x27 => Some(UnitKind::EvolvedSpiritArcher),
            0x28 => Some(UnitKind::EvolvedMekanik),
            0x29 => Some(UnitKind::EvolvedKneecapper),
            0x2a => Some(UnitKind::EvolvedWormTower),
            0x2b => Some(UnitKind::EvolvedBallistaBattery),
            0x2c => Some(UnitKind::EvolvedTouchofDeath),
            0x2d => Some(UnitKind::EvolvedBombardierMegaBeetl),
            0x2e => Some(UnitKind::EvolvedMissileCrab),
            0x2f => Some(UnitKind::EvolvedCrinoid),
            0x30 => Some(UnitKind::EvolvedDeathHippo),
            0x31 => Some(UnitKind::EvolvedDireWolf),
            0x36 => Some(UnitKind::EvolvedWarMastodon),
            0x37 => Some(UnitKind::EvolvedMobileDerrick),
            0x38 => Some(UnitKind::EvolvedMobileClanHall),
            0x39 => Some(UnitKind::EvolvedPitScorpion),
            0x3a => Some(UnitKind::EvolvedBullAntTanker),
            0x3b => Some(UnitKind::EvolvedSkeletalWall),
            0x3c => Some(UnitKind::EvolvedSpiritWall),
            0x3d => Some(UnitKind::Series9CropDuster),
            0x3f => Some(UnitKind::Series9AgResponsebot),
            0x40 => Some(UnitKind::Series9TransportDome),
            0x41 => Some(UnitKind::Series9WeaponControl),
            0x42 => Some(UnitKind::Series9MicrounitFactory),
            0x43 => Some(UnitKind::Series9Windmill),
            0x44 => Some(UnitKind::Series9WindTurbine),
            0x45 => Some(UnitKind::Series9DrillRig),
            0x46 => Some(UnitKind::Series9MacrounitFactory),
            0x47 => Some(UnitKind::Series9Barn),
            0x48 => Some(UnitKind::Series9PowerStation),
            0x49 => Some(UnitKind::Series9MaintenanceDepot),
            0x4a => Some(UnitKind::Series9Technostudy),
            0x4d => Some(UnitKind::Series9WeedKiller),
            0x4e => Some(UnitKind::Series9PodLauncher),
            0x4f => Some(UnitKind::Series9Seeder),
            0x50 => Some(UnitKind::Series9Michaelangelo),
            0x51 => Some(UnitKind::Series9Pollinator),
            0x52 => Some(UnitKind::Series9Deseeder),
            0x53 => Some(UnitKind::Series9Systech),
            0x54 => Some(UnitKind::Series9DistanceSeeder),
            0x55 => Some(UnitKind::Series9PodCannon),
            0x56 => Some(UnitKind::Series9SolarIntensifier),
            0x57 => Some(UnitKind::Series9BugZapper),
            0x58 => Some(UnitKind::Series9Cauteriser),
            0x59 => Some(UnitKind::Series9DoomDome),
            0x5e => Some(UnitKind::Series9GrimReaper),
            0x5f => Some(UnitKind::Series9MobileOilbot),
            0x60 => Some(UnitKind::Series9MobileBarn),
            0x61 => Some(UnitKind::Series9Patrolbot),
            0x62 => Some(UnitKind::Series9Radiator),
            0x63 => Some(UnitKind::Series9Responsebot),
            0x64 => Some(UnitKind::Series9Tankbot),
            0x65 => Some(UnitKind::Series9OilTankerbot),
            0x66 => Some(UnitKind::Series9PowerHedge),
            0x67 => Some(UnitKind::Series9LaserWall),
            0x68 => Some(UnitKind::SurvivorWilburBomber),
            0x6a => Some(UnitKind::SurvivorOrvilleFighter),
            0x6b => Some(UnitKind::SurvivorTransportChopper),
            0x6c => Some(UnitKind::SurvivorArmoury),
            0x6d => Some(UnitKind::SurvivorBarracks),
            0x6e => Some(UnitKind::SurvivorSolarCollector),
            0x6f => Some(UnitKind::SurvivorSolarConvertor),
            0x70 => Some(UnitKind::SurvivorDrillRig),
            0x71 => Some(UnitKind::SurvivorMachineShop),
            0x72 => Some(UnitKind::SurvivorOutpost),
            0x73 => Some(UnitKind::SurvivorPowerStation),
            0x74 => Some(UnitKind::SurvivorRepairBay),
            0x75 => Some(UnitKind::SurvivorResearchLaboratory),
            0x76 => Some(UnitKind::SurvivorCaptive),
            0x79 => Some(UnitKind::SurvivorFlamer),
            0x7a => Some(UnitKind::SurvivorGrenadier),
            0x7b => Some(UnitKind::SurvivorMachineGunner),
            0x7c => Some(UnitKind::SurvivorKamikaze),
            0x7d => Some(UnitKind::SurvivorGuidedRocketeer),
            0x7e => Some(UnitKind::SurvivorLaserRifleman),
            0x7f => Some(UnitKind::SurvivorTechnician),
            0x80 => Some(UnitKind::SurvivorLightDefenseTower),
            0x81 => Some(UnitKind::SurvivorCannonTower),
            0x82 => Some(UnitKind::SurvivorAaTower),
            0x83 => Some(UnitKind::SurvivorLaserDestroyer),
            0x84 => Some(UnitKind::SurvivorAtv),
            0x85 => Some(UnitKind::SurvivorAnacondaTank),
            0x86 => Some(UnitKind::SurvivorAutocannonTank),
            0x87 => Some(UnitKind::SurvivorBarrageCraft),
            0x88 => Some(UnitKind::SurvivorDirtBike),
            0x8d => Some(UnitKind::SurvivorHoverBuggy),
            0x8e => Some(UnitKind::SurvivorJuggernaut),
            0x8f => Some(UnitKind::SurvivorMobileDrillRig),
            0x90 => Some(UnitKind::SurvivorMobileOutpost),
            0x91 => Some(UnitKind::SurvivorOilTanker),
            0x92 => Some(UnitKind::SurvivorHydrorockWall),
            0x93 => Some(UnitKind::SurvivorSolarWall),
            0x94 => Some(UnitKind::Tech21stCenturyDropship),
            0x97 => Some(UnitKind::Tech21stCenturyGortRobot),
            0x98 => Some(UnitKind::Tech21stCenturyMechanoidWalker),
            0x99 => Some(UnitKind::Tech21stCenturyPlasmaTankMk2),
            0x9a => Some(UnitKind::Tech21stCenturySentinelDroid),
            0x9b => Some(UnitKind::Tech21stCenturyTechBunker),
            0x9c => Some(UnitKind::Tech21stCenturyUfo),
            0xa9 => Some(UnitKind::Ripple),
            _ => None,
        }
    }
}
